alias be="bundle exec"
alias bl="bundle list"
alias bp="bundle package"
alias bo="bundle open"
alias bout="bundle outdated"
alias bu="bundle update"
alias bi="bundle install"
alias bcn="bundle clean"
alias coverage="COVERAGE=true bundle exec rspec"
export BUNDLE_PATH="${GEM_HOME}"
